### ISSUE TITLE
make getEasterMonthAndDay function available in npm/yarn

### ISSUE THREAD

**Issue by dabela** [amaidah/luxon-business-days#34]
How would you import the getEasterMonthAndDay function from ./helpers when the package is installed from yarn or npm?

Looking through node_modules it seems that the src directory is not there so it cannot be imported directly.

The reason for using this is that sometimes one may need to know the date of Easter and then add a holiday based on this date. e.g. Good Friday which is a holiday in some countries.

**Comment by amaidah** [comment]
Thanks for opening an issue -- just confirming that I saw it for now.

**Comment by amaidah** [comment]
Is Good Friday the only holiday that needs the Easter date?

**Comment by dabela** [comment]
Not necessarily across all cultures..you might get someone who wants Easter Monday which is a bank holiday in some countries.

 My request was to expose the Easter calculation function so others can do whatever they need based on Easter when customising holidays.


----
Duncan

**Comment by amaidah** [comment]
Thanks, this has been made available in [v2.8.0](https://github.com/amaidah/luxon-business-days/releases/tag/v2.8.0).
