### ISSUE TITLE
plusBusiness does not retain time zone in some cases

### ISSUE THREAD

**Issue by toddoglethorpe** [amaidah/luxon-business-days#35]
Thanks for this very useful library. I expected that calling `plusBusiness` would retain the time zone but it appears that isn't happening. 

Here's an [example sandbox](https://codesandbox.io/s/throbbing-wave-7v107?file=/src/index.js) that shows if you call `plusBusiness` on a DateTime in UTC, the resulting DateTime will be in the local time zone instead of UTC.

I don't see anything in the docs or tests concerning time zones, but it seems likely this is not intended behavior.

Thanks

**Comment by amaidah** [comment]
Thank you for the clear explanation and example sandbox. I'll look into it.

**Comment by buzzguy** [comment]
this would be very useful

**Comment by cwilso03** [comment]
The same bug appears on `minusBusiness()` calls, too.  A workaround for now is to call luxon's `setZone()` method after calling `minusBusiness()`.

**Comment by amaidah** [comment]
This has been fixed in latest release: https://github.com/amaidah/luxon-business-days/releases/tag/v2.8.2.

Thanks for being patient!
