### ISSUE TITLE
Luxon 2.0

### ISSUE THREAD

**Issue by bkatbeh** [amaidah/luxon-business-days#55]
Hello!

Is there any plan to update luxon-business-days to support newly released Luxon 2.0?

Thanks!

**Comment by amaidah** [comment]
Yep, hoping to find some time for it

**Comment by skwasha** [comment]
FWIW - According to the migration notes, none of the changes should affect this package. Anecdotally, I bumped the luxon version to 2.0.1 locally and didn't run into any issues. Note, I did not run a full battery of tests.

**Comment by jgclark** [comment]
If I read it right, PR #68 makes this small update.

**Comment by amaidah** [comment]
luxon-business-days `3.0.1` now supports luxon `^3.x`. Thanks for being patient: https://github.com/amaidah/luxon-business-days/releases/tag/v3.0.1
