### ISSUE TITLE
`plusBusiness`/`minusBusiness` do not work properly with default holiday matchers

### ISSUE THREAD

**Issue by att14** [amaidah/luxon-business-days#60]
This is because many of the holiday matchers do an object comparison of the two datetimes. For example, the `isThanksgivingDay` returns `+inst === +thanksgivingDay` when it should return something like the Christmas matcher `matchesMonth && matchesDay`.

```js
const { DateTime } = require('luxon-business-days');

const dt = DateTime.local();
const { availableHolidayMatchers } = dt;

availableHolidayMatchers.isThanksgivingDay(
  DateTime.fromObject({ day: 25, month: 11, year: 2021 })
)
// true

availableHolidayMatchers.isThanksgivingDay(
  DateTime.fromObject({ day: 25, month: 11, year: 2021, zone: 'UTC' })
)
// false

availableHolidayMatchers.isThanksgivingDay(
  DateTime.fromObject({ day: 25, month: 11, year: 2021, hour: 1 })
)
// false
```

**Comment by amaidah** [comment]
Thanks, merged the fix. There may be a potential followup where in your second example, can you you have Xmas start in one zone and compared across a different zone where it's not yet Xmas? Is it a potential issue in comparisons?

Thinking aloud, if a business is global and has started Xmas in one region and someone is checking if it's xmas in another region where it is not yet Xmas, `DateTime.now()` would not match the day so I think it's probably fine.
