### ISSUE TITLE
Registering custom holidayMatcher is not working.

### ISSUE THREAD

**Issue by siarmehri** [amaidah/luxon-business-days#70]
Adding custom holidayMatchers didn't work for me I used the example of isCelebratingKobe function changed the dates, plusBusiness is not taking into consideration the dates in isCelebratingKobe at all.

Can one help me in this regards please?

**Comment by ketzalv** [comment]
I have the same problem, can't override the holiday days

**Comment by amaidah** [comment]
Could you please provide a reproduction in CodeSandbox? It works for me: https://codesandbox.io/s/luxon-business-days-holiday-ovveride-example-b18v5i?file=/src/index.js
